export const PROJECTS = [
  {
    slug: "zara",
    name1: "Zara",
    name2: "Home",
    services: "research / design / art direction / motion",
    role: "lead designer",
    year: "2022",
    cover: "/projects/zara-home-preview.webp",
    detail: {
      title: "Zara Home",
      caseStudyUrl: "https://www.behance.net/gallery/141241379/ZARA-HOME-2022",
      text1:
        "A student project that outgrew its brief. Full e-commerce redesign for Zara Home — homepage, catalogue, product page, cart, and checkout.",
      text2:
        "The question wasn't how to make it prettier. It was how to make a shopping experience feel like browsing a magazine.",
      email: "nikkoz.hello@gmail.com",
      images: [
        "/projects/zara-home/zara-home__internal-01.webp",
        "/projects/zara-home/zara-home__internal-02.webp",
        "/projects/zara-home/zara-home__internal-03.webp",
        "/projects/zara-home/zara-home__internal-04.webp",
        "/projects/zara-home/zara-home__internal-05.webp",
        "/projects/zara-home/zara-home__internal-06.webp",
        "/projects/zara-home/zara-home__internal-07.webp",
      ],
    },
  },
  {
    slug: "xerox",
    name1: "Xerox",
    name2: "PARC",
    services: "research / design / art direction / motion",
    role: "lead designer",
    year: "2022",
    cover: "/projects/xerox-preview.webp",
    detail: {
      title: "Xerox PARC",
      caseStudyUrl: "https://www.behance.net/gallery/146216141/Xerox-PARC-2022",
      text1: "This is an interactive editorial experience about a laboratory that was fifty years ahead of its time — built from archival photography, original research, and a lot of time spent in the past.",
      text2: "History is the best design brief. Everything PARC built came from one question: what should computing feel like for a human being? That question is still worth asking.",
      email: "nikkoz.hello@gmail.com",
      images: [
        "/projects/xerox/xerox__internal-01.webp",
        "/projects/xerox/xerox__internal-02.webp",
        "/projects/xerox/xerox__internal-03.webp",
        "/projects/xerox/xerox__internal-04.webp",
        "/projects/xerox/xerox__internal-05.webp",
        "/projects/xerox/xerox__internal-06.webp",
        "/projects/xerox/xerox__internal-07.webp",
      ],
    },
  },
  {
    slug: "volvo",
    name1: "Volvo",
    name2: "S90",
    services: "research / design / art direction / motion / 3d",
    role: "lead designer",
    year: "2023",
    cover: "/projects/volvo-preview.webp",
    detail: {
      title: "Volvo S90",
      caseStudyUrl: "https://www.behance.net/gallery/182654399/Volvo-S90-Recharge-Web-3D-Experiment",
      text1: "Car websites are among the most expensive in the world to produce — and among the most boring to use. This is a concept for Volvo S90 Recharge that asks what happens when you treat a car configurator like an editorial experience.",
      text2: "The car is not the product. The feeling of owning it is. Every automotive website gets this wrong — they show specs when they should be selling a state of mind.",
      email: "nikkoz.hello@gmail.com",
      images: [
        "/projects/volvo/volvo__internal-01.webp",
        "/projects/volvo/volvo__internal-02.webp",
        "/projects/volvo/volvo__internal-03.webp",
        "/projects/volvo/volvo__internal-04.webp",
        "/projects/volvo/volvo__internal-05.webp",
        "/projects/volvo/volvo__internal-06.webp",
        "/projects/volvo/volvo__internal-07.webp",
      ],
    },
  },
  {
    slug: "sephora",
    name2: "Sephora",
    services: "research / design / art direction / motion",
    role: "lead designer",
    year: "2024",
    cover: "/projects/sephora-preview.webp",
    detail: {
      title: "Sephora",
      caseStudyUrl: "https://www.behance.net/gallery/195998503/Sephora-eCommerce",
      text1: "Full redesign of Sephora.com — homepage, catalogue, product page, search. The brief was simple: make it feel like walking into the store. The store is dark, sensual, curated. The website was generic e-commerce. This is the gap I closed.",
      text2: "Luxury is not about adding more. It's about removing everything that doesn't belong. Every section of this redesign asked one question: does this feel like Sephora, or does it feel like everyone else?",
      email: "nikkoz.hello@gmail.com",
      images: [
        "/projects/sephora/sephora__internal-01.webp",
        "/projects/sephora/sephora__internal-02.webp",
        "/projects/sephora/sephora__internal-03.webp",
        "/projects/sephora/sephora__internal-04.webp",
        "/projects/sephora/sephora__internal-05.webp",
        "/projects/sephora/sephora__internal-06.webp",
        "/projects/sephora/sephora__internal-07.webp",
      ],
    },
  },
];

export function getProjectBySlug(slug) {
  return PROJECTS.find((p) => p.slug === slug) || null;
}
